
export CHART = prometheus
export MODULE = .
export NAMESPACE = prometheus
export REPO = prometheus
export URL = https://prometheus-community.github.io/helm-charts
export VERSION = 15.10.4

include ../Makefile
