
export CHART = spark-operator
export MODULE = .
export NAMESPACE = spark 
export REPO = spark-operator
export URL = https://googlecloudplatform.github.io/spark-on-k8s-operator
export VERSION = 1.1.25

include ../Makefile
