
export CHART = alertmanager
export MODULE = .
export NAMESPACE = alertmanager
export REPO = prometheus
export URL = https://prometheus-community.github.io/helm-charts
export VERSION = 0.18.3

include ../Makefile
