datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
        access: proxy
        isDefault: true

extraConfigmapMounts:
  - name: opsbot-ca-cert
    configMap: opsbots-tls-ca
    mountPath: /etc/ssl/certs/ca-certificates.crt
    subPath: opsbot.pem
    readOnly: false

grafana.ini:
  auth:
    disable_login_form: true
    oauth_auto_login: true
  auth.generic_oauth:
    allow_sign_up: true
    api_url: https://keycloak.lo/realms/master/protocol/openid-connect/userinfo
    auth_url: https://keycloak.lo/realms/master/protocol/openid-connect/auth
    client_id: grafana
    client_secret: 5DQkq4zKqM0aJKj7U6JRG3ESQ369tgmu
    enabled: true
    name: Keycloak
    role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'
    scopes: profile,email,groups
    token_url: https://keycloak.lo/realms/master/protocol/openid-connect/token
  analytics:
    check_for_updates: true
  grafana_net:
    url: https://grafana.net
  log:
    mode: console
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  server:
    root_url: https://grafana.lo

ingress:
  annotations:
    cert-manager.io/cluster-issuer: opsbots
  enabled: true
  hosts:
    - grafana.lo
  tls:
    - hosts:
        - grafana.lo
      secretName: grafana-tls
