hub:
  config:
    Authenticator:
      auto_login: true
      enable_auth_state: true

    GenericOAuthenticator:
      client_id: jhub
      client_secret: XNCgasXD4zD5FN8oQC5yZLLYvIHnMm8o
      oauth_callback_url: https://jupyterhub.lo/hub/oauth_callback
      authorize_url: https://keycloak.lo/realms/master/protocol/openid-connect/auth
      token_url: https://keycloak.lo/realms/master/protocol/openid-connect/token
      userdata_url: https://keycloak.lo/realms/master/protocol/openid-connect/userinfo
      login_service: keycloak
      username_key: preferred_username
      userdata_params:
        state: state

    JupyterHub:
      authenticator_class: generic-oauth

  extraEnv:
    - name: OAUTH2_TLS_VERIFY
      value: "0"
    - name: OAUTH2_AUTHORIZE_URL
      value: http://keycloak.lo/realms/master/protocol/openid-connect/auth
    - name: OAUTH2_TOKEN_URL
      value: http://keycloak.lo/realms/master/protocol/openid-connect/token

ingress:
  annotations:
    cert-manager.io/cluster-issuer: opsbots
  enabled: true
  hosts:
    - jupyterhub.lo
  tls:
    - hosts:
        - jupyterhub.local
      secretName: jupyterhub-local-tls

proxy:
  service:
    type: NodePort
