apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger:
      "LimitRanger plugin set: cpu, memory request for container
      minio; cpu, memory limit for container minio"
  creationTimestamp: "2022-07-17T20:05:14Z"
  generateName: minio-ml-workshop-7fcc5dfd8-
  labels:
    app.kubernetes.io/instance: min
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 0.0.1
    component.opendatahub.io/name: minio
    helm.sh/chart: s3-server-0.0.1
    opendatahub.io/component: "false"
    pod-template-hash: 7fcc5dfd8
  name: minio-ml-workshop-7fcc5dfd8-z5b85
  namespace: ml-workshop
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: minio-ml-workshop-7fcc5dfd8
      uid: 311785ff-8b98-4dcd-979e-f4b2b23e4759
  resourceVersion: "6817"
  uid: b547c4c4-0131-4049-a688-f6647eecdaa1
spec:
  containers:
    - args:
        - server
        - /storage
        - --console-address=:33933
      env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minio123
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_TRACE
          value: "true"
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio123
      image: docker.io/minio/minio:latest
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 10
        httpGet:
          path: /minio/health/live
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 30
      name: minio
      ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 33933
          protocol: TCP
      readinessProbe:
        failureThreshold: 10
        httpGet:
          path: /minio/health/ready
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 30
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 500Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /storage
          name: storage
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-mxdr5
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-mlops
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: minio-ml-workshop
    - name: kube-api-access-mxdr5
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
