apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger:
      "LimitRanger plugin set: cpu, memory request for container
      oauth-proxy; cpu, memory limit for container oauth-proxy; memory request for
      container mlflow-deployment; cpu, memory limit for container mlflow-deployment;
      cpu, memory request for init container oauthproxy; cpu, memory limit for init
      container oauthproxy"
  creationTimestamp: "2022-07-17T20:05:14Z"
  generateName: mlflow-c4df77c7d-
  labels:
    app: mlflow
    component.opendatahub.io/name: mlflow
    opendatahub.io/component: "false"
    pod-template-hash: c4df77c7d
  name: mlflow-c4df77c7d-8wp48
  namespace: ml-workshop
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: mlflow-c4df77c7d
      uid: c31c6e11-affc-4629-8e93-97b958ef615b
  resourceVersion: "12661"
  uid: c8ff12fc-6784-4b2c-ac7a-369e5cb84bd7
spec:
  containers:
    - args:
        - --provider=keycloak-oidc
        - --https-address=
        - --http-address=:5000
        - --client-id=mflow
        - --client-secret=ad216993-cf3a-4742-ba17-b531d5c22046
        - --upstream=http://localhost:5500
        - --email-domain=*
        - --cookie-secret=ad12ca-qw23asd55adcwbjep
        - --oidc-issuer-url=https://keycloak.minikube.local/auth/realms/master
        - --allowed-role=mflow:admin
        - --reverse-proxy=true
        - --skip-provider-button=true
        - --ssl-insecure-skip-verify=true
        - --ssl-upstream-insecure-skip-verify=true
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
      imagePullPolicy: IfNotPresent
      name: oauth-proxy
      ports:
        - containerPort: 5000
          name: public
          protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 500Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-ghdmd
          readOnly: true
    - args:
        - mlflow
        - server
        - --host=0.0.0.0
        - --port=5500
        - --backend-store-uri=postgresql://postgres:admin@mlflow-db:5432/postgres
        - --default-artifact-root=s3://mlflow/
        - --workers=2
      env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio-ml-workshop:9000/
        - name: AWS_ACCESS_KEY_ID
          value: minio
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: mlflow-store
        - name: AWS_BUCKET_NAME
          value: mlflow
        - name: MLFLOW_S3_IGNORE_TLS
          value: "true"
      image: quay.io/ml-aml-workshop/mlflow:0.0.2
      imagePullPolicy: Always
      name: mlflow-deployment
      ports:
        - containerPort: 5500
          name: http
          protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-ghdmd
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
    - command:
        - sh
        - -c
        - until nslookup mlflow-db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
          do echo waiting for mlflow db service; sleep 2; done
      image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest
      imagePullPolicy: Always
      name: oauthproxy
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 500Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-ghdmd
          readOnly: true
  nodeName: k8s-mlops
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: mlflow-proxy
  serviceAccountName: mlflow-proxy
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-ghdmd
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
