apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger:
      "LimitRanger plugin set: cpu, memory request for container
      manager; cpu, memory limit for container manager"
  creationTimestamp: "2022-07-17T20:05:15Z"
  generateName: seldon-controller-manager-c5f59c56d-
  labels:
    app: seldon
    app.kubernetes.io/instance: seldon1
    app.kubernetes.io/name: seldon
    app.kubernetes.io/version: v0.5
    control-plane: seldon-controller-manager
    pod-template-hash: c5f59c56d
  name: seldon-controller-manager-c5f59c56d-rmcwb
  namespace: ml-workshop
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: seldon-controller-manager-c5f59c56d
      uid: ce5ecfb5-349d-4db2-ba5a-1598c90de1ae
  resourceVersion: "9020"
  uid: e94c5271-38cc-4d3c-8c47-f3f5592ed2b1
spec:
  containers:
    - args:
        - --enable-leader-election
        - --webhook-port=8443
        - --create-resources=true
      command:
        - /manager
      env:
        - name: WATCH_NAMESPACE
          value: ml-workshop
        - name: RELATED_IMAGE_EXECUTOR
          value: docker.io/seldonio/seldon-core-executor:1.12.0
        - name: RELATED_IMAGE_ENGINE
          value: docker.io/seldonio/seldon-engine:1.12.0
        - name: RELATED_IMAGE_STORAGE_INITIALIZER
          value: docker.io/seldonio/storage-initializer:1.12.0
        - name: RELATED_IMAGE_SKLEARNSERVER
          value: docker.io/seldonio/sklearnserver:1.12.0
        - name: RELATED_IMAGE_XGBOOSTSERVER
          value: docker.io/seldonio/xgboostserver:1.12.0
        - name: RELATED_IMAGE_MLFLOWSERVER
          value: docker.io/seldonio/mlflowserver:1.12.0
        - name: RELATED_IMAGE_TFPROXY
          value: docker.io/seldonio/tfproxy:1.12.0
        - name: RELATED_IMAGE_TENSORFLOW
          value: docker.io/seldonio/tensorflow-serving:1.12.0
        - name: MANAGER_CREATE_RESOURCES
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONTROLLER_ID
        - name: AMBASSADOR_ENABLED
          value: "true"
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "false"
        - name: ENGINE_CONTAINER_IMAGE_AND_VERSION
          value: docker.io/seldonio/engine:1.7.0
        - name: ENGINE_CONTAINER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: ENGINE_CONTAINER_SERVICE_ACCOUNT_NAME
          value: default
        - name: ENGINE_CONTAINER_USER
        - name: ENGINE_LOG_MESSAGES_EXTERNALLY
          value: "false"
        - name: PREDICTIVE_UNIT_SERVICE_PORT
          value: "9000"
        - name: PREDICTIVE_UNIT_DEFAULT_ENV_SECRET_REF_NAME
        - name: PREDICTIVE_UNIT_METRICS_PORT_NAME
          value: metrics
        - name: ENGINE_SERVER_GRPC_PORT
          value: "5001"
        - name: ENGINE_SERVER_PORT
          value: "8000"
        - name: ENGINE_PROMETHEUS_PATH
          value: /prometheus
        - name: ISTIO_ENABLED
          value: "false"
        - name: KEDA_ENABLED
          value: "false"
        - name: ISTIO_GATEWAY
          value: istio-system/seldon-gateway
        - name: ISTIO_TLS_MODE
        - name: USE_EXECUTOR
          value: "true"
        - name: EXECUTOR_CONTAINER_IMAGE_AND_VERSION
          value: seldonio/seldon-core-executor:1.7.0
        - name: EXECUTOR_CONTAINER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: EXECUTOR_PROMETHEUS_PATH
          value: /prometheus
        - name: EXECUTOR_SERVER_PORT
          value: "8000"
        - name: EXECUTOR_CONTAINER_USER
        - name: EXECUTOR_CONTAINER_SERVICE_ACCOUNT_NAME
          value: default
        - name: EXECUTOR_SERVER_METRICS_PORT_NAME
          value: metrics
        - name: EXECUTOR_REQUEST_LOGGER_DEFAULT_ENDPOINT
          value: http://default-broker
        - name: DEFAULT_USER_ID
        - name: EXECUTOR_DEFAULT_CPU_REQUEST
          value: "0.5"
        - name: EXECUTOR_DEFAULT_MEMORY_REQUEST
          value: 512Mi
        - name: EXECUTOR_DEFAULT_CPU_LIMIT
          value: "0.5"
        - name: EXECUTOR_DEFAULT_MEMORY_LIMIT
          value: 512Mi
        - name: ENGINE_DEFAULT_CPU_REQUEST
          value: "0.5"
        - name: ENGINE_DEFAULT_MEMORY_REQUEST
          value: 512Mi
        - name: ENGINE_DEFAULT_CPU_LIMIT
          value: "0.5"
        - name: ENGINE_DEFAULT_MEMORY_LIMIT
          value: 512Mi
      image: docker.io/seldonio/seldon-core-operator:1.12.0
      imagePullPolicy: IfNotPresent
      name: manager
      ports:
        - containerPort: 8443
          name: webhook-server
          protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 500Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-7t555
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-mlops
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: seldon-manager
  serviceAccountName: seldon-manager
  terminationGracePeriodSeconds: 10
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-7t555
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
